version: '3'
services:
  ganache:
    image: trufflesuite/ganache-cli:v6.6.0
    command: ganache -d
    ports:
      - "9999:8545"

  deployer:
    build: .
    command: "sh -c '
      apk add jq;
      SADDLE_BUILD=/build npx saddle compile;
      GAS=6721975 SADDLE_BUILD=/build npx saddle deploy OpenOraclePriceData;
      GAS=6721975 SADDLE_BUILD=/build npx saddle deploy DelFiPrice $$(cat /build/development.json | jq -r .OpenOraclePriceData) $$REPORTER_1_ADDRESS,$$REPORTER_2_ADDRESS:array
    '"
    environment:
      - PROVIDER=http://ganache:8545
    env_file:
      - test_keys.env
    depends_on:
      - ganache
    volumes:
      - ./.dockerbuild:/build

  reporter-1:
    build: sdk/javascript
    command: npm run start --
      --private_key $$REPORTER_1_PRIVATE_KEY
      --script examples/fixed.js
    ports:
      - "3001:3000"
    env_file:
      - test_keys.env

  reporter-2:
    build: sdk/javascript
    command: npm run start --
      --private_key $$REPORTER_2_PRIVATE_KEY
      --script examples/fixed.js
    ports:
      - "3002:3000"
    env_file:
      - test_keys.env

  poster:
    build: poster
    command: "sh -c '
      apk add jq;
      while [ ! -f /build/development.json ]; do echo waiting for /build/development.json; sleep 1; done;
      cat /build/development.json
      npm run start --
      --poster_key $$POSTER_KEY
      --sources http://reporter-1:3000/prices.json,http://reporter-2:3000/prices.json
      --view_address $$(cat /build/development.json | jq -r .DelFiPrice)
      --web3_provider http://ganache:8545
    '"
    depends_on:
      - deployer 
      - reporter-1
      - reporter-2
    restart: "always"
    volumes:
      - ./.dockerbuild:/build
    env_file:
      - test_keys.env
