version: 2.1

jobs:
  test_oracle:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo
    steps:
      - run:
        |
          sudo wget https://github.com/ethereum/solidity/releases/download/v0.5.9/solc-static-linux -O /usr/local/bin/solc
          sudo chmod +x /usr/local/bin/solc
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit-oracle
      - run: JEST_JUNIT_OUTPUT=~/junit-oracle/test-results.xml yarn run test --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ~/junit-oracle
      - store_artifacts:
          path: ~/junit-oracle

  test_poster:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo/poster
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-poster-dependencies-{{ checksum "package.json" }}
          - v1-poster-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-poster-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit-poster
      - run: JEST_JUNIT_OUTPUT=~/junit-poster/test-results.xml yarn run test --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ~/junit-poster
      - store_artifacts:
          path: ~/junit-poster

  test_reporter_javascript:
    docker:
      - image: circleci/node:11
    working_directory: ~/repo/sdk/javascript
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
          - v1-sdk-javascript-dependencies-{{ checksum "package.json" }}
          - v1-sdk-javascript-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-sdk-javascript-dependencies-{{ checksum "package.json" }}
      - run: mkdir ~/junit-sdk-javascript
      - run: JEST_JUNIT_OUTPUT=~/junit-sdk-javascript/test-results.xml yarn run test --ci --reporters=default --reporters=jest-junit
      - store_test_results:
          path: ~/junit-sdk-javascript
      - store_artifacts:
          path: ~/junit-sdk-javascript

workflows:
  version: 2
  test:
    jobs:
      - test_oracle
      - test_poster
      - test_reporter_javascript
